### ISSUE TITLE
Acer Nitro 5

### ISSUE THREAD

**Issue by ghost** [linrunner/tlp-doc#12]
Hi there, Acer Nitro 5 has 80% battery limit officially on windows through Acer Care Center App, could you make it possible on Linux

**Comment by linrunner** [comment]
Hi, 

this is not the TLP issue tracker, but the one for the docsite. 

Regarding your topic: there is already an issue about it (https://github.com/linrunner/TLP/issues/596). But since there is no kernel interface for charge thresholds for Acer laptops, an implementation of your request is currently not possible.

**Comment by ghost** [comment]
Ah cool
