### ISSUE TITLE
Fedora 37 gpg fingerprint

### ISSUE THREAD

**Issue by belamu** [linrunner/tlp-doc#14]
When upgrading Fedora to a new version (in my case 35->36) it asks to check the TLP Repository GPG key. It is missing for Fedora 37 (just released) on https://linrunner.de/tlp/installation/fedora.html#fingerprints . Can you add it?

**Comment by belamu** [comment]
Updating to Fedora 37 asks:
```
GPG-Schlüssel 0x779FE8EE wird importiert:
 Benutzerkennung  : »TLP Repository for Fedora (37) <tlp@warpnine.de>«
 Fingerabdruck: 666F 0F62 9C09 5486 7FA9 7C55 4E41 F248 779F E8EE
 Von          : /etc/pki/rpm-gpg/RPM-GPG-KEY-tlp-37
Is this ok [y/N]:
```

**Comment by linrunner** [comment]
Hi,

I have forwarded your question to the maintainer of the repository.

But: do you _really_ need the repo? Kernels >= 5.17 already contain all ThinkPad battery care features. No need for acpi-call anymore - and therefore it is not contained in the repo since F36 --> https://linrunner.de/tlp/installation/fedora.html#thinkpads-only-external-kernel-modules

**Comment by belamu** [comment]
Thank you for the information. Since I installed and configured tlp for me before Fedora 36 and of course didn't remember this detail, I wasn't aware of this change.

**Comment by linrunner** [comment]
Done. Thanks for the hint.

https://github.com/linrunner/tlp-doc/pull/15
